Feature/delete pattern count cms 1315
PrimarySite/django-redis pull request #2
Opened 2016-09-21 16:01 UTC by komar

2016-09-22 09:33 UTC, cleder commented on django_redis/client/sharded.py
> +    def delete_pattern(self, pattern, version=None, client=None, count=None):
test for this - maybe with fakeredis or mockredis?

2016-09-22 09:33 UTC, amusikal commented on django_redis/cache.py
> +DJANGO_REDIS_DELETE_PATTERN_SCAN_COUNT = getattr(settings, "DJANGO_REDIS_DELETE_PATTERN_SCAN_COUNT", 10)
Much nicer :bow:

2016-09-22 09:34 UTC, cleder requested changes
I'd like to see a test for `delete_pattern`

2016-09-22 09:37 UTC, amusikal approved these changes
I'd love to see more tests and little pep8s on this, but given that it's a fork... yolo

Nice changes!

2016-09-22 09:42 UTC, amusikal commented on django_redis/client/sharded.py
> +        }
Single line should be fine for this, unless this is normal for the package.

2016-09-22 09:50 UTC, komar commented on django_redis/client/sharded.py
> +    def delete_pattern(self, pattern, version=None, client=None, count=None):
Agreed. This is a test i mentioned in the standup. Since fakeredis is already in place the test is going to use it.

2016-09-22 10:08 UTC, komar commented on django_redis/cache.py
> +DJANGO_REDIS_DELETE_PATTERN_SCAN_COUNT = getattr(settings, "DJANGO_REDIS_DELETE_PATTERN_SCAN_COUNT", 10)
I have actually found in some other function the library's code:
 
```
    def iter_keys(self, search, itersize=None, client=None, version=None):
        """
        Same as keys, but uses redis >= 2.8 cursors
        for make memory efficient keys iteration.
        """

        if client is None:
            client = self.get_client(write=False)

        pattern = self.make_key(search, version=version)
        for item in client.scan_iter(match=pattern, count=itersize):
            item = smart_text(item)
            yield self.reverse_key(item)
```
which makes me think that i will change this name to `DJANGO_REDIS_SCAN_ITERSIZE` to be more consistent with naming. What do you think?

2016-09-23 10:37 UTC, amusikal approved these changes
:white_check_mark: Lovely stuff

2016-09-23 10:38 UTC, amusikal approved these changes

2016-09-23 11:13 UTC, cleder approved these changes
lgtm

2016-09-23 11:13 UTC, cleder approved these changes
lgtm

2016-09-23 14:20 UTC, merged